---
name: docker-broker

addons:
- name: bpm
  jobs:
  - name: bpm
    release: bpm

instance_groups:
- name: subway
  azs: [z1]
  instances: 1
  vm_type: minimal
  stemcell: trusty
  networks: [{name: default}]
  jobs:
  - name: subway-broker
    release: cf-subway
    consumes:
      backend:
        from: backend
    provides:
      subway:
        as: broker
        shared: true
    properties:
      username: broker
      password: ((subway-broker-password))
      name: docker-broker

- name: docker
  azs: [z1,z2,z3]
  instances: 1
  persistent_disk: 65536
  vm_type: minimal
  stemcell: trusty
  networks: [{name: default}]
  jobs:
  - name: docker
    release: docker
    properties:
      tcp_address: 0.0.0.0
      tls_cacert: "((docker-tls.ca))"
      tls_cert: "((docker-tls.certificate))"
      tls_key: "((docker-tls.private_key))"

  - name: cf-containers-broker
    release: cf-containers-broker
    provides:
      cf-containers-broker:
        as: backend
        shared: true
    properties:
      username: broker
      password: ((docker-broker-password))
      cookie_secret: ((docker-broker-cookie-secret))
      max_containers: 20
      fetch_images: true
      services: []

- name: sanity-test
  azs: [z1]
  lifecycle: errand
  instances: 1
  vm_type: minimal
  stemcell: trusty
  networks: [{name: default}]
  jobs:
  - name: sanity-test-broker
    release: cf-containers-broker
    consumes:
      servicebroker:
        from: broker
      docker-broker-catalog:
        from: backend
  - name: docker
    release: docker
    properties:
      tcp_address: 0.0.0.0
      tls_cacert: "((docker-tls.ca))"
      tls_cert: "((docker-tls.certificate))"
      tls_key: "((docker-tls.private_key))"

variables:
- name: subway-broker-password
  type: password
- name: docker-broker-password
  type: password
- name: docker-broker-cookie-secret
  type: password
- name: docker-ca
  type: certificate
  options:
    is_ca: true
    common_name: dockerCA
- name: docker-tls
  type: certificate
  options:
    ca: docker-ca
    common_name: docker
    extended_key_usage:
    - client_auth

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: 3541.latest

update:
  canaries: 1
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  max_in_flight: 1
  serial: false

releases:
- name: bpm
  sha1: 6d99c62b0993e4f8ff747faa62f91b4288cc27bf
  url: https://s3.amazonaws.com/cf-containers-broker-boshrelease/compiled-releases/bpm/bpm-0.5.0-ubuntu-trusty-3541.12-20180427-023829-890304456-20180427023837.tgz
  version: 0.5.0
- name: cf-subway
  sha1: 70b1ec6bc9a44ebcfe5ce2f89c1bcdf4c7d08f81
  url: https://s3.amazonaws.com/cf-containers-broker-boshrelease/compiled-releases/cf-subway/cf-subway-3.2.0-ubuntu-trusty-3541.12-20180427-023906-453709332-20180427023911.tgz
  version: 3.2.0
- name: docker
  sha1: 9396ffc58da6724b7d656809c062a7a862e5973a
  url: https://s3.amazonaws.com/cf-containers-broker-boshrelease/compiled-releases/docker/docker-32.0.0-ubuntu-trusty-3541.12-20180427-000536-650949482-20180427000544.tgz
  version: 32.0.0
- name: cf-containers-broker
  sha1: 16a27577419810515c8596aa0d431943c5581ce9
  url: https://s3.amazonaws.com/cf-containers-broker-boshrelease/compiled-releases/cf-containers-broker/cf-containers-broker-1.0.3-ubuntu-trusty-3541.12-20180427-023757-468867249-20180427023801.tgz
  version: 1.0.3
